package com.thejv04.noteapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a note in the application.
 *
 * @property id Unique identifier, auto-generated by Room.
 * @property title Title of the note.
 * @property content Text content of the note.
 * @property timestamp Creation or last modification time in milliseconds.
 * @property color Color associated with the note (default 0 = no color).
 * @property isChecklist Whether the note is a checklist or plain text.
 * @property checklistItems Checklist items serialized as a JSON string.
 * @property imageUris Comma-separated URIs of attached images.
 */

@Entity(tableName = "notes")
data class Note(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val title: String,
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val color: Int = 0,
    val isChecklist: Boolean = false,
    val checklistItems: String = "",
    val imageUris: String = ""
)